CREATE TABLE [dbo].[Queue] (
    [Id]  UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [Uri] VARCHAR (130)    NOT NULL,
    CONSTRAINT [PK_Queue] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_Queue]
    ON [dbo].[Queue]([Uri] ASC);

